name: Gitleaks Secret Scanner
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
permissions:
  read-all
jobs:
  gitleaks:
    name: Detect secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7  # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
